### ISSUE TITLE
Chipped 1.18.2-1.2.2 [FORGE] file is named chipped-1.18.2-1.2.1-forge.jar

### ISSUE THREAD

**Issue by pavog** [CookieCNetwork/Chipped#140]
Hi,

when I download [Chipped 1.18.2-1.2.2 [FORGE]](https://www.curseforge.com/minecraft/mc-mods/chipped/files/3748664) I get a file named `chipped-1.18.2-1.2.1-forge.jar`.
When I compare the file with the real [Chipped 1.18.2-1.2.1 [FORGE]](https://www.curseforge.com/minecraft/mc-mods/chipped/files/3745340) release, I can see that it is not the same file because the MD5 checksums are different.

- [Chipped 1.18.2-1.2.2 [FORGE]](https://www.curseforge.com/minecraft/mc-mods/chipped/files/3748664) - Filename: chipped-1.18.2-1.2.1-forge.jar - MD5: 0f8bf6b5fe1fd27436d41dd8c7b399d7 
- [Chipped 1.18.2-1.2.1 [FORGE]](https://www.curseforge.com/minecraft/mc-mods/chipped/files/3745340) - Filename: chipped-1.18.2-1.2.1-forge.jar - MD5: e00600bdba852ca9e226983204858a75 

I guess that you just named the file for Chipped 1.2.2 wrong.
This may confuse some other users too. 
Can you rename the file behind this [Chipped 1.18.2-1.2.2 [FORGE]](https://www.curseforge.com/minecraft/mc-mods/chipped/files/3748664) from `chipped-1.18.2-1.2.1-forge.jar` to `chipped-1.18.2-1.2.2-forge.jar`?

**Comment by terrariumearth** [comment]
Fixed next update

**Comment by pavog** [comment]
This doesn't really solve the problem I pointed out in this issue, but thanks.
