### ISSUE TITLE
Workbenches and shaders

### ISSUE THREAD

**Issue by InfornoFire** [CookieCNetwork/Chipped#24]
Top part is shadowed

**Comment by terrariumearth** [comment]
fixed in 1.0.2 patch

**Comment by Larch0** [comment]
I still have the top parts of workbenches shadowed with shaders on , even on the latest version , can someone help perhaps ?
