### ISSUE TITLE
If a chipped lantern touches water, the game crashes.

### ISSUE THREAD

**Issue by Prime-Fuchsia** [CookieCNetwork/Chipped#58]
Chipped 1.1 for Forge. My latest Crash Report is also attached.
Optifine was installed, tested with and without shaders and it happened both times.
Happens every time, and worst of all once it happens, trying to load to world from this point onwards will crash before you can do anything.

Really want to use this mod but the fact that it murders the world on top of crashing is too spooky for me even if the crash is easily avoidable. Apologies if this is my fault

Here is my minecraft log from just before the crash to me alt-f4ing:

[21:38:44] [Server thread/INFO] [minecraft/MinecraftServer]: [LimitFM: Gave 64    [Lantern] to LimitFM]
[21:38:44] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] Gave 64    [Lantern] to LimitFM
[21:38:44] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 3351 advancements
[21:38:53] [Server thread/INFO] [minecraft/MinecraftServer]: [LimitFM: Gave 1    [Water Bucket] to LimitFM]
[21:38:53] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] Gave 1    [Water Bucket] to LimitFM
[21:38:56] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID ebf9897a-a670-4fdb-b44e-68dada10b4a7
[21:38:56] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception while ticking
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}
Caused by: java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{chipped:special_lantern_2}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at net.minecraft.block.IWaterLoggable.func_204510_a(SourceFile:15) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.fluid.FlowingFluid.func_211761_a(FlowingFluid.java:371) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_211760_a(FlowingFluid.java:302) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_205571_a(FlowingFluid.java:270) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_205572_b(FlowingFluid.java:351) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_207937_a(FlowingFluid.java:138) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_205575_a(FlowingFluid.java:125) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_207191_a(FlowingFluid.java:410) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FluidState.func_206880_a(FluidState.java:70) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerWorld.func_205339_a(ServerWorld.java:583) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerTickListMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:337) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	... 5 more
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
[crash-2021-06-29_21.38.56-server.txt](https://github.com/CookieCNetwork/Chipped/files/6732377/crash-2021-06-29_21.38.56-server.txt)

**Comment by Prime-Fuchsia** [comment]
After testing a little bit more this seems to only happen with the fat lanterns.I know nothing about anything related to modding or minecraft but I hope this information was useful

**Comment by MsRandom** [comment]
Fixed by 1.1.1.

**Comment by Stormalisk** [comment]
Still happening on the latest version 1.1.2 with the large soul lanterns, bug will corrupt world (crash on relog) unless mod is removed or downgraded.

Here is the crash report:
https://drive.google.com/file/d/1ZmWQG2cl97775IW5roAT7lPQBqmH8Gg-/view?usp=sharing

**Comment by Stormalisk** [comment]
This crash happens even if chipped is the only mod present
https://drive.google.com/file/d/1ULJnD1W58tVQh2aONypIBMHlrZyBmJXF/view?usp=sharing

**Comment by NielsPilgaard** [comment]
This issue is still happening: https://github.com/NillerMedDild/Enigmatica6/issues/3443

crash report: https://paste.feed-the-beast.com/view/7daf0bb4#L14
